/**
 * The palette is declared here rather than inherited from the framework's
 * defaults, so every colour the ticket uses is generated by name and no
 * utility can silently resolve to nothing.
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        // Instrument chassis grey, lightest to darkest.
        chassis: {
          50: '#f2f5f3',
          100: '#e9edea',
          200: '#d2d8d4',
          300: '#b1b9b5',
          400: '#98a19d',
          500: '#838c88',
          600: '#5a615e',
          700: '#363c39',
          800: '#232825',
          850: '#1a1e1c',
          900: '#141715',
          950: '#0d0f0e',
        },
        // The single accent, carried only by the number being decided.
        signal: {
          DEFAULT: '#4fd08a',
          dim: '#2f8a5c',
        },
        // Reserved for a rate that has gone stale.
        alert: {
          DEFAULT: '#e0a338',
          dim: '#8a6522',
        },
        // Reserved for an input the calculator cannot act on.
        fault: {
          DEFAULT: '#ef7a68',
        },
      },
      fontFamily: {
        sans: ['"Roboto Condensed"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"Roboto Condensed"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        figure: ['clamp(1.7rem, 8vw, 2.75rem)', { lineHeight: '1', letterSpacing: '-0.03em' }],
      },
    },
  },
  plugins: [],
};
